### ISSUE TITLE
Filter is not properly escaping single quotes in the where clause

### ISSUE THREAD

**Issue by chris-fox** [Esri/crowdsource-manager#252]
If you enable a filter on a text field and ask for values, if you pass in a string that contains a single quote it will return no results even when there are matching results. For example if you search for the string "Trader Joe's", it will return no results even when there is a value of "Trader Joe's" in the field.

This where clause is being passed to the service:
where = appname = 'Trader Joe's'

The correct clause should be:
where = appname = 'Trader Joe''s'

This works correctly in the web map.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Is this something that could be addressed for 6.1?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

We are analysing this issue and will update you on this.

--Pratik Gohil

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

> Is this something that could be addressed for 6.1?

Yes, we can include this in 6.1

--Pratik Gohil

**Comment by allisonmuise** [comment]
Thanks!

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

We have fixed this issue and will be available in upcoming code drop.

--Pratik Gohil

**Comment by allisonmuise** [comment]
@CTLocalGovTeam I am still seeing this issue : http://localgovtestdev.mapsdevext.arcgis.com/apps/CrowdsourceManager/index.html?appid=c8960073c12b413b818a7b27d82d71e0

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

We have fixed this issue and will be delivered in the upcoming code drop on Friday, March 16.

--Pratik Gohil

**Comment by allisonmuise** [comment]
verified
